# Generated by Django 4.1 on 2022-08-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0, null=0, verbose_name='Кол-во просмотров'),
            preserve_default=False,
        ),
    ]
