# Generated by Django 4.1 on 2022-08-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='Категории', to='articles.category'),
        ),
        migrations.DeleteModel(
            name='ArtCat',
        ),
    ]
