# Generated by Django 4.1 on 2022-08-24 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 9, 41, 30, 742504, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
