# Generated by Django 4.1 on 2022-08-25 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 16, 48, 30, 492905, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
