# Generated by Django 4.1 on 2022-08-29 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='', upload_to='media/uploads/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 12, 48, 20, 190208, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
