# Generated by Django 4.1 on 2022-08-29 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_img_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='Описание не заданно', max_length=150, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default='', upload_to='uploads/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 13, 20, 11, 136565, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название статьи'),
        ),
    ]
